# In service 
# 1. 'alpine_postgres', the 'container_name' or 'hostname' both can be used to connect as server name, 
#     the environment 'POSTGRES_SERVER' in 'alpine_liquibase' must keep the same with it

version: "3"
services:

    # The service name 'alpine_postgres' can be recognized as the contianer's hostname to connect!
    alpine_postgres:
        build: 
            context: ../alpine_postgres
        image: leiwang008/alpine_postgres
        # The 'container_name' can be recognized as the contianer's hostname to connect!
        # container_name: alpine_postgres 
        # The 'hostname' can be recognized as the contianer's hostname to connect!
        hostname: alpine_postgres 
        ports:
            - "5432:5432"
        command: 
            - postgres
        networks:
            - database_network
        environment:
            - POSTGRES_PASSWORD=secretpass
            - POSTGRES_USER=rttest
            - POSTGRES_DB=rtdb 

    alpine_liquibase:
        build: 
            context: .
            args: 
                - ARG_LIQUIBASE_HOME=/liquihome
        image: leiwang008/alpine_liquibase
        container_name: alpine_liquibase
        command:
            # - config
            - update
        networks:
            - database_network
        volumes: 
            - "./changelogs:/liquibase/changelogs"
        environment:
            # the environment 'POSTGRES_SERVER' should keep the same value as alpine_postgres's service name or its hostname or its container_name
            - POSTGRES_SERVER=alpine_postgres
            # 'POSTGRES_DB', 'POSTGRES_USER' and 'POSTGRES_PASSWORD' should use the same value as in service 'alpine_postgres'.
            - POSTGRES_DB=rtdb
            - POSTGRES_USER=rttest
            - POSTGRES_PASSWORD=secretpass
            # if 'LIQUIBASE_URL' is specified, 'POSTGRES_SERVER' and 'POSTGRES_DB' will be ignored
            # - LIQUIBASE_URL="jdbc:postgresql://alpine_postgres:5432/rtdb"
        depends_on: 
            - alpine_postgres

networks:
    database_network:

    # default:
    #     external: true
    #     name: database_network